### ISSUE TITLE
Error while running OTP Request?

### ISSUE THREAD

**Issue by shubhamgoel4aug** [souvikdc9/aadhaarapi.net#5]
Additional information: '=' is an unexpected token. The expected token is ';'. Line 1197, position 72.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at Uidai.Aadhaar.Agency.ApiClient`2.<GetResponseXmlAsync>d__25.MoveNext() in C:\Users\Shubh Rocks Goel\Downloads\Compressed\aadhaarapi.net-master\aadhaarapi.net-master\Source\src\Uidai.Aadhaar\Agency\ApiClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Uidai.Aadhaar.Agency.ApiClient`2.<GetResponseAsync>d__22.MoveNext() in C:\Users\Shubh Rocks Goel\Downloads\Compressed\aadhaarapi.net-master\aadhaarapi.net-master\Source\src\Uidai.Aadhaar\Agency\ApiClient.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Uidai.Aadhaar.Agency.ApiClient`2.<GetResponseAsync>d__21.MoveNext() in C:\Users\Shubh Rocks Goel\Downloads\Compressed\aadhaarapi.net-master\aadhaarapi.net-master\Source\src\Uidai.Aadhaar\Agency\ApiClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Uidai.Aadhaar.Sample.Otp.<GenerateOtpAsync>d__8.MoveNext() in C:\Users\Shubh Rocks Goel\Downloads\Compressed\aadhaarapi.net-master\aadhaarapi.net-master\Source\src\Uidai.Aadhaar.Sample\Otp.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Uidai.Aadhaar.Sample.Program.Main(String[] args) in C:\Users\Shubh Rocks Goel\Downloads\Compressed\aadhaarapi.net-master\aadhaarapi.net-master\Source\src\Uidai.Aadhaar.Sample\Program.cs:line 30

**Comment by ghost** [comment]
Review the HTTP status code. I couldn't reproduce the issue.
